### PR TITLE
Use the regexp data type for hiera_source

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by jlambert121** [comment]
I like this, travis is upset though.  What version of puppet supports a Regex type?

**Comment by roidelapluie** [comment]
I am testing with 4.2

**Comment by jlambert121** [comment]
I've bumped the module to require puppet >= 4.2, can you rebase this so we can make sure it works?  I'm fine keeping this puppet module with the newest version of puppet.

**Comment by roidelapluie** [comment]
@jlambert121 sorry but it fails with 4.2 tests.

However "puppet parser validate" thinks it's fine. So there is a bug in the test toolchain.

**Comment by roidelapluie** [comment]
```
$ grep Regex manifests/init.pp
  Optional[Regexp[/^puppet/]]                  $hiera_source      = $::puppet::params::hiera_source,
$ puppet parser validate manifests/init.pp
$ echo $?
0
```

**Comment by jlambert121** [comment]
So it looks like puppet-lint needs a patch merged (https://github.com/rodjek/puppet-lint/pull/435) for this to work.  I'll either disable the linter or set this up to run off of a fork.  I will get it figured out tomorrow, I need to cut a release.

**Pull request closed without merging**
